{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<section id="ezmailjetapiv3_subscribe">
    <form>
        <p>Want to subscribe to our newsletter ?</p>
        <input type="email" placeholder="Your e-mail" id="ezmailjetapiv3_subscribe_email">
        <input type="submit" value="Subscribe" id="ezmailjetapiv3_subscribe_submit">
    </form>
</section>