{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<section id="ezmailjetapiv3_subscribe">
    <form>
        <p>{'Want to subscribe to our newsletter ?'|i18n('mailjet/inscription')}</p>
        <input type="email" placeholder="{'Your e-mail'|i18n('mailjet/inscription')}" id="ezmailjetapiv3_subscribe_email">
        <input type="submit" value="{'Subscribe'|i18n('mailjet/inscription')}" id="ezmailjetapiv3_subscribe_submit">
    </form>
</section>